#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file
 */

$autoload = getcwd() . '/vendor/autoload.php';
$yii2 = getcwd() . '/vendor/yiisoft/yii2/Yii.php';

if (!is_file($autoload)) {
    die('You need to set up the project dependencies using Composer');
}

if (!is_file($yii2)) {
    die('You need to set up yii2 using composer');
}

require_once $autoload;
require_once Builder::path('defines');
require_once $yii2;

Yii::setAlias('@root', getcwd());
Yii::setAlias('@vendor', getcwd() . '/vendor');

(function () {
    $config = require_once hiqdev\composer\config\Builder::path('console');
    (new yii\console\Application($config))->run();
})();
